version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "AdmiringWorm"
    default_labels:
      - "dependencies"
      - ".NET"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "AdmiringWorm"
    default_labels:
      - "dependencies"
      - "javascript"
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "AdmiringWorm"
    default_labels:
      - "dependencies"
      - "submodules"
